name: Build 7Miner

on:
  push:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller --onefile 7Miner.py
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-windows-x64
          path: dist/7Miner.exe

  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller --onefile --target-arch x86 7Miner.py || echo "x86 not supported on this runner"
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-windows-x86
          path: dist/7Miner.exe

  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller --onefile 7Miner.py
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-linux-x64
          path: dist/7Miner

  build-linux-x86:
    runs-on: ubuntu-latest
    container: i386/ubuntu
    steps:
      - uses: actions/checkout@v3
      - run: apt update && apt install -y python3 python3-pip
      - run: pip3 install pyinstaller
      - run: pyinstaller --onefile 7Miner.py
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-linux-x86
          path: dist/7Miner

  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/app \
            -w /app arm64v8/python:3.11-slim \
            /bin/sh -c "pip install pyinstaller && pyinstaller --onefile 7Miner.py"
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-linux-arm64
          path: dist/7Miner

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller --onefile 7Miner.py
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-macos-x64
          path: dist/7Miner

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: arch -arm64 pyinstaller --onefile 7Miner.py || echo "arm64 build fallback"
      - uses: actions/upload-artifact@v4
        with:
          name: 7Miner-macos-arm64
          path: dist/7Miner
