name: Build 7Miner multiplataforma

on:
  push:
    branches: [main, principal]
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows Build (x64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller -r requirements.txt
      - run: pyinstaller 7Miner.py --onefile --name 7Miner
      - run: mkdir dist-final && mv dist/7Miner.exe dist-final/7Miner-windows-x64.exe
      - uses: actions/upload-artifact@v3
        with:
          name: 7Miner-windows-x64
          path: dist-final/*

  build-linux:
    name: Linux Build (x64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller -r requirements.txt
      - run: pyinstaller 7Miner.py --onefile --name 7Miner
      - run: mkdir dist-final && mv dist/7Miner dist-final/7Miner-linux-x64
      - uses: actions/upload-artifact@v3
        with:
          name: 7Miner-linux-x64
          path: dist-final/*

  build-mac:
    name: macOS Build (x64)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller -r requirements.txt
      - run: pyinstaller 7Miner.py --onefile --name 7Miner
      - run: mkdir dist-final && mv dist/7Miner dist-final/7Miner-macos-x64
      - uses: actions/upload-artifact@v3
        with:
          name: 7Miner-macos-x64
          path: dist-final/*

  build-linux-arm:
    name: Linux ARM Build (via cross-compilation)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências do cross-build
        run: |
          sudo apt update
          sudo apt install -y python3-pyinstaller
          pip install pyinstaller
      - run: pyinstaller 7Miner.py --onefile --name 7Miner
      - run: mkdir dist-final && mv dist/7Miner dist-final/7Miner-linux-arm
      - uses: actions/upload-artifact@v3
        with:
          name: 7Miner-linux-arm
          path: dist-final/*

  build-mac-arm64:
    name: macOS ARM64 (Apple Silicon)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install pyinstaller -r requirements.txt
          pyinstaller 7Miner.py --onefile --name 7Miner
          mkdir dist-final && mv dist/7Miner dist-final/7Miner-macos-arm64
      - uses: actions/upload-artifact@v3
        with:
          name: 7Miner-macos-arm64
          path: dist-final/*
