name: Build 7Miner

on:
  push:
    branches: [ "principal", "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build com PyInstaller
        run: |
          pyinstaller 7Miner.py --onefile --name 7Miner

      - name: Upload do executável
        uses: actions/upload-artifact@v3
        with:
          name: 7Miner-${{ matrix.os }}
          path: |
            dist/7Miner*
