name: Build 7Miner

on:
  push:
    branches: [ "main", "principal" ] # mude conforme o nome da sua branch principal
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Construir com PyInstaller
        run: |
          pyinstaller --onefile 7Miner.py
        shell: bash

      - name: Upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: 7Miner-${{ runner.os }}
          path: dist/7Miner*
